version: '2.1'

services:
  db:
    image: mysql
    container_name: db
    ports:
    - "3306:3306"
    environment:
      MYSQL_DATABASE: crud
      MYSQL_ROOT_PASSWORD: 1234
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 5

  crud:
    depends_on:
        db:
          condition: service_healthy
    build:
      dockerfile: Dockerfile
      context: .
    ports:
    - "8000:9000"
#    - "5005:5005"
    restart: always
    links:
      - db:db_host