version: '3'

services:
  db:
    image: mysql
    container_name: db
    ports:
    - "3306:3306"
    environment:
      MYSQL_DATABASE: crud
      MYSQL_ROOT_PASSWORD: 1234

  crud:
    depends_on:
      - db
    build:
      dockerfile: Dockerfile
      context: .
    ports:
    - "8000:9000"
    restart: always
    links:
      - db:db_host