spring:
  application:
    name: crud

driverClassName: com.mysql.cj.jdbc.Driver
url: jdbc:mysql://db_host:3306/crud?useSSL=false&allowPublicKeyRetrieval=true
username: root
password: 1234

server:
  port: 9000
